const FORM_KEY = process.env.REACT_APP_BROVKO_FORM_KEY;

export const addOrderRequestTemplate = {
  form: FORM_KEY,
  getResultData: '1',
  products: [
    {
      id: '',
      name: '',
      costPerItem: '',
      amount: '',
      description: '',
      sku: '',
    },
  ],
  comment: '',
  fName: '',
  lName: '',
  mName: '',
  phone: '',
  email: '',
  con_comment: '',
  shipping_method: '',
  payment_method: '',
  shipping_address: '',
  novaposhta: {
    ServiceType: '',
    payer: 'recipient',
    area: '',
    region: '',
    city: '',
    cityNameFormat: 'full',
    WarehouseNumber: '',
    Street: '',
    BuildingNumber: '',
    Flat: '',
  },
  commission: '',
  ukrposhta: {
    ServiceType: '',
    payer: '',
    type: '',
    city: '',
    WarehouseNumber: '',
    Street: '',
    BuildingNumber: '',
    Flat: '',
  },
  sajt: '',
  organizationId: '',
  shipping_costs: '',
  stockId: '',
  prodex24source_full: '',
  prodex24source: '',
  prodex24medium: '',
  prodex24campaign: '',
  prodex24content: '',
  prodex24term: '',
  prodex24page: '',
};
